"""永続化の抽象（実装は infrastructure）。"""

from typing import Protocol
from uuid import UUID

from showcase.domain.breed import Breed
from showcase.domain.dog import Dog
from showcase.domain.email import Email
from showcase.domain.owner import Owner
from showcase.domain.owner_id import OwnerId


class OwnerRepository(Protocol):
    def get_by_id(self, owner_id: OwnerId) -> Owner | None: ...
    def get_by_email(self, email: Email) -> Owner | None: ...
    def save(self, owner: Owner) -> None: ...
    def is_email_registered(self, email: Email) -> bool: ...
    def is_handle_taken(
        self, normalized_handle: str, *, exclude_owner_id: OwnerId | None = None
    ) -> bool: ...
    def register_with_password(self, owner: Owner, password: str) -> None: ...


class BreedRepository(Protocol):
    """犬種マスタ。主キーは code（int）。"""

    def get_by_code(self, code: int) -> Breed | None: ...
    def list_ordered(self) -> list[Breed]: ...
    def save(self, breed: Breed) -> None: ...


class DogRepository(Protocol):
    def delete_by_id_for_owner(self, owner_id: OwnerId, dog_id: UUID) -> int: ...
    def get_by_id(self, dog_id: UUID) -> Dog | None: ...
    def get_by_id_for_owner(self, owner_id: OwnerId, dog_id: UUID) -> Dog | None: ...
    def list_all_ordered(self) -> list[Dog]: ...
    def list_by_owner(self, owner_id: OwnerId) -> list[Dog]: ...
    def save(self, dog: Dog) -> None: ...
